resolver: lts-16.27

system-ghc: true
skip-ghc-check: true

nix:
  enable: false
  packages: [zlib.dev, zlib.out]

packages:
- .

allow-newer: true

extra-deps:
  - hakyll-images-1.1.0
  # - MissingH-1.4.3.0
  # - hakyll-4.14.1.0
